version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - mv target/solicitacao_equipamento ./
artifacts:
  files:
    - target/solicitacao_equipamento.war
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'